name: webapp
services:
  backend:
    image: ghcr.io/fulsep/backend:latest
    ports:
      - 8888:8888
  frontend:
    image: ghcr.io/fulsep/frontend:latest
    ports:
      - 3000:3000
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1