name: tickhub
services:
  backend:
    image: golang:1.23-alpine
    ports:
      - 8888:8888
  frontend:
    image: node:lts-alpine
    ports:
      - 3000:3000
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=1
